#!/usr/bin/env bash
# harden-demo.sh — make an installation fit to be reachable from the internet.
#
# The compose file and the local runner carry development credentials on
# purpose: `crp_password_dev` in plain sight is honest about what it is, and a
# developer should not have to hunt for a secret to start the platform. The
# moment the same installation answers on a public address, every one of them is
# a way in, and the signing key in deployments/jwt is a way to mint any
# identity's token.
#
# This writes a .env next to the compose file with generated values, and a fresh
# RSA pair. It never prints a secret: they go to files with mode 600, and the
# summary says where.
#
#   ./scripts/harden-demo.sh                    generate what is missing
#   ./scripts/harden-demo.sh --rotate           replace what is already there
#   ./scripts/harden-demo.sh --host demo.example.com
#
# It does not configure TLS. Terminate HTTPS in front — a reverse proxy with a
# certificate — because nothing here should be reachable in the clear, and
# because the interface's sign-in flow sets cookies that a browser only keeps
# over HTTPS on a public host.
set -euo pipefail

BACKEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$BACKEND_DIR/deployments/.env"
JWT_DIR="$BACKEND_DIR/deployments/jwt"

ROTATE=0
HOST=""
while [[ $# -gt 0 ]]; do
	case "$1" in
		--rotate) ROTATE=1; shift ;;
		--host)   HOST="${2:?--host needs a value}"; shift 2 ;;
		*) echo "usage: $0 [--rotate] [--host NAME]" >&2; exit 2 ;;
	esac
done

secret() { openssl rand -base64 32 | tr -d '\n=' | tr '+/' '-_'; }

if [[ -f "$ENV_FILE" && $ROTATE -eq 0 ]]; then
	echo "→ $ENV_FILE exists; keeping it (pass --rotate to replace)"
else
	umask 077
	mkdir -p "$(dirname "$ENV_FILE")"
	cat > "$ENV_FILE" <<-EOF
		# Generated by scripts/harden-demo.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
		# Not for version control: deployments/.env is ignored.
		CRP_PG_PASSWORD=$(secret)
		CRP_REDIS_PASSWORD=$(secret)
		CRP_NEO4J_PASSWORD=$(secret)
		CLICKHOUSE_PASSWORD=$(secret)
		KEYCLOAK_ADMIN_PASSWORD=$(secret)
		KEYCLOAK_CLIENT_SECRET=$(secret)
		NEXTAUTH_SECRET=$(secret)
		VAULT_DEV_ROOT_TOKEN_ID=$(secret)
	EOF
	echo "→ wrote $ENV_FILE (mode $(stat -c %a "$ENV_FILE"))"
fi

# The origins the services accept, and the address the interface calls.
#
# Left at localhost on a public host, the browser blocks every call the
# interface makes and each panel reports "Failed to fetch" with nothing in any
# log to explain it.
if [[ -n "$HOST" ]]; then
	grep -v '^CRP_CORS_ORIGINS=\|^NEXTAUTH_URL=\|^CRP_OIDC_ISSUER=' "$ENV_FILE" > "$ENV_FILE.tmp"
	mv "$ENV_FILE.tmp" "$ENV_FILE"
	cat >> "$ENV_FILE" <<-EOF
		CRP_CORS_ORIGINS=https://$HOST
		NEXTAUTH_URL=https://$HOST
		CRP_OIDC_ISSUER=https://$HOST/realms/cyberradar
	EOF
	chmod 600 "$ENV_FILE"
	echo "→ origins and issuer set to https://$HOST"
else
	echo "→ no --host given: origins stay as they are, which is right for a laptop"
fi

# A signing key that ships with the repository signs anybody's token. The pair
# under deployments/jwt is a development pair for exactly that reason.
if [[ -f "$JWT_DIR/private.pem" && $ROTATE -eq 0 ]]; then
	echo "→ $JWT_DIR/private.pem exists; keeping it (pass --rotate to replace)"
	echo "  if this installation will be public, rotate: every token signed by the old key stays valid otherwise"
else
	umask 077
	mkdir -p "$JWT_DIR"
	openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$JWT_DIR/private.pem" 2>/dev/null
	openssl rsa -in "$JWT_DIR/private.pem" -pubout -out "$JWT_DIR/public.pem" 2>/dev/null
	chmod 600 "$JWT_DIR/private.pem"
	chmod 644 "$JWT_DIR/public.pem"
	echo "→ new RSA pair in $JWT_DIR (private key mode $(stat -c %a "$JWT_DIR/private.pem"))"
fi

cat <<'EOF'

Ce qui reste à faire, et que ce script ne fait pas :

  1. HTTPS devant. Rien ici ne doit répondre en clair.
  2. Les ports. Seuls 3000 (interface) et 8080 (Keycloak) ont une raison
     d'être joignables. Les 30 ports de service, PostgreSQL, ClickHouse,
     Kafka, Neo4j, Redis, Vault, Prometheus, Grafana et Jaeger n'en ont
     aucune : fermez-les au pare-feu.
  3. Le mot de passe de l'administrateur de démonstration, qui est dans
     migrations/seed/001_identities.sql et donc dans le dépôt.
  4. Relire deployments/docker-compose.yml : les valeurs par défaut y
     restent, le .env les remplace, et une variable oubliée reprend la
     valeur de développement sans le dire.

Et le piège qui fait perdre une heure : PostgreSQL, ClickHouse et Neo4j ne
lisent leur mot de passe qu'à la création de leur volume. Changer le .env
d'une installation déjà démarrée ne change rien côté serveur — les services
présenteront le nouveau mot de passe à un serveur qui garde l'ancien, et
l'erreur sera une authentification refusée sans rapport apparent avec ce
fichier. Durcissez donc avant le premier démarrage, ou détruisez les volumes :

    docker compose -f deployments/docker-compose.yml down -v
EOF
